voucherMe/urls.py
from django.urls import path
from voucherMe import views

app_name = 'voucherMe'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('business/', views.all_businesses, name='all_businesses'),
    path('posts/', views.all_posts, name='all_posts'),
    path('search/<str:type>', views.search, name='search'),
    path('<str:username>/business/add_business/', views.add_business, name='add_business'),
    path('business/<slug:business_name_slug>/', views.show_business, name='show_business'),
    path('business/<slug:business_name_slug>/add_post/', views.add_post, name='add_post'),
    path('business/<slug:business_name_slug>/<int:post_id>/', views.show_post, name='show_post'),
    path('add_data/', views.add_data, name='add_data'),
]

voucher_me_project/urls.py
#CHARLIE

"""voucher_me_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include
from voucherMe import views
from voucherMe.forms import UserProfileForm

urlpatterns = [
    path('', views.index, name='index'),
    path('voucher/', include('voucherMe.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voucherMe/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

TAGS_CATEGORY = (
    ("1", "FOOD"),
    ("2", "TRAVEL"),
    ("3", "FASHION"),
    ("4", "TECHNOLOGY"),
    ("5", "BOOKS"),
    ("6", "MUSIC"),
    ("7", "FURNITURE"),
    ("8", "STATIONARY & ART"),
    ("9", "SKINCARE & BEAUTY"),
)
TAGS_TYPE = (
    ("1", "FLASH SALE/DISCOUNT"),
    ("2", "BUY MORE, SAVE MORE"),
    ("3", "LOTTERY/COMPETITION"),
    ("4", "GIFT BUNDLE/GIVEAWAY"),
    ("5", "BUY 1 GET 1 FREE"),
    ("6", "LOYALTY PROGRAM"),
    ("7", "VOUCHER/COUPON"),
    ("8", "FREE SHIPPING/RETURN"),
    ("9", "OTHER"),
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

class Business(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=1024, unique=False)
    image = models.ImageField(upload_to='business_images', blank=True)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Businesses'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Business, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    

class Post(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, default=0)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=1024)
    promo = models.CharField(max_length=50, blank=True)
    tags_category = models.CharField(max_length=32, choices=TAGS_CATEGORY, default=1)
    tags_type = models.CharField(max_length=32, choices=TAGS_TYPE, default=1)
    visits = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        for field_name in ['promo']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(Post, self).save(*args, **kwargs)

voucherMe/forms.py
from django import forms
from django.contrib.auth.models import User
from voucherMe.models import Business, Post, UserProfile
from django.contrib.auth.forms import UserCreationForm

TAGS_CATEGORY = (
    ("1", "FOOD"),
    ("2", "TRAVEL"),
    ("3", "FASHION"),
    ("4", "TECHNOLOGY"),
    ("5", "BOOKS"),
    ("6", "MUSIC"),
    ("7", "FURNITURE"),
    ("8", "STATIONARY & ART"),
    ("9", "SKINCARE & BEAUTY"),
)
TAGS_TYPE = (
    ("1", "FLASH SALE/DISCOUNT"),
    ("2", "BUY MORE, SAVE MORE"),
    ("3", "LOTTERY/COMPETITION"),
    ("4", "GIFT BUNDLE/GIVEAWAY"),
    ("5", "BUY 1 GET 1 FREE"),
    ("6", "LOYALTY PROGRAM"),
    ("7", "VOUCHER/COUPON"),
    ("8", "FREE SHIPPING/RETURN"),
    ("9", "OTHER"),
)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(UserCreationForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)


class BusinessForm(forms.ModelForm):
    name = forms.CharField(max_length=50, help_text="What's your business called?")
    description = forms.CharField(widget=forms.Textarea, max_length=1024,
                                  help_text="Add a catchy description for your business!")
    slug = forms.CharField(widget=forms.HiddenInput, required=False)
    image = forms.ImageField(help_text="Attach a logo!", required=False)

    class Meta:
        model = Business
        fields = ('name', 'description')
        exclude = ('user',)


class PostForm(forms.ModelForm):
    name = forms.CharField(max_length=50, help_text="Your post's name goes here.")
    description = forms.CharField(widget=forms.Textarea, max_length=1024,
                                  help_text="What is this post about?")
    promo = forms.CharField(max_length=50, help_text="Add a promo code (if you want!)", required=False)
    tags_category = forms.ChoiceField(help_text="Add a category tag", choices=TAGS_CATEGORY)
    tags_type = forms.ChoiceField(help_text="Add a type tag", choices=TAGS_TYPE)
    visits = forms.IntegerField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Post
        fields = ('name', 'description', 'promo', 'tags_category', 'tags_type',)
        exclude = ('business', 'visits',)

templates/voucher/about.html
{% extends "voucher/base.html" %}
{% load static %}

{% block title_block %}About Us!{% endblock %}

{% block body_block %}
    <div class="jumbotron p-1" style="background-color: aliceblue">
         <div class="container">
             <h2 align="center">About VoucherMe!</h2>
         </div>
     </div>
   

    <center>
	<p class="text" style="width: 62%; text-align: justify">
        VoucherMe provides a platform for businesses to advertise by posting regular updates on their business’s growth/development while also posting exclusive offers on time-limited promo codes, schemes or vouchers.
        Users can view this information without registering to the web app and can upvote a business’s post if they’re interested in it. This would enable businesses to keep track of their marketing trends and site effectiveness by gaining valuable feedback.
        Businesses can build their profile to attract more customers by attaching external links to their websites/resources or posting frequently.
        Businesses can also look at the schemes/advertising strategies of other businesses to get an outlook of their competition and make relevant business decisions thereon.
    </p><br/>
	<img src="{% static 'images/about.jpg' %}" alt="Picture of a voucher" style="width: 34%; height: 9%"/>
	<br/><br/><br/>
        <p class="text" style="width: 62%; text-align: justify">
            VoucherMe was created by Harvey Cameron-Sproull and Aaryan Pagar as part of their WAD2 assessed exercise (for which they obviously got an A1).
        </p>
	<br/>
    </center>
	{% endblock %}

templates/voucher/add_business.html
{% extends "voucher/base.html" %}
 {% block title_block %}
		Create business!
 {% endblock %}

<link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

{% block body_block %}
    <div class="jumbotron p-1">
    <h3 align="center">Create a new Business</h3>
    </div>
    <div class="container">
        <div class="row">
            <form role="form" method="post" action="{% url 'voucherMe:add_business' user.username %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name" class="sr-only">Name</label>
                    <input type="text" name="name" id="id_name" class="form-control"
                           placeholder="What's your business called?" required autocapitalize="words" style="margin-bottom: 6px; width: 120%"><br/>
                    <label for="id_description" class="sr-only">Description</label>
                    <textarea class="form-control" rows="6" name="description" id="id_description"
                              placeholder="What is your business about?" autocapitalize="sentences" style="width: 140%"></textarea><br/>
                    <label for="id_image" class="sr-only">Image</label>
                    <input type="text" class="form-control" readonly id="id_image" placeholder="Add a logo for your business" style="width: 80%;">
                    <input type="file" name="image" id="id_image" class="form-control"
                           placeholder="Add a logo for your business" autofocus style="margin-bottom: 6px; padding-bottom: 12%; width: 80%"><br/>
                </div>

                <button class="btn btn-primary" type="submit" name="submit">
                    Create Business!
                </button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endblock %}

templates/voucher/add_post.html
{% extends "voucher/base.html" %}
 {% block title_block %}
		Add Post!
 {% endblock %}
{% block body_block %}
    {% ifequal user business.user %}
    <div class="jumbotron p-1">
    <h3 align="center">Add a new Post for {{ business.name }}</h3>
    </div>
    <div class="container">
        <div class="row">
            <form role="form" method="post" action="{% url 'voucherMe:add_post' business.slug %}" enctype= multipart/form-data>
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name" class="sr-only">Name</label>
                    <input type="text" name="name" id="id_name" class="form-control"
                           placeholder="Add a name for you post" required autocapitalize="words" style="margin-bottom: 6px; width: 130%"><br/>
                    <label for="id_description" class="sr-only">Description</label>
                    <textarea class="form-control" rows="6" name="description" id="id_description"
                              placeholder="Describe your post" autocapitalize="sentences" style="width: 130%"></textarea><br/>
                    <label for="id_promo" class="sr-only">Promo</label>
                    <input type="text" name="promo" id="id_promo" class="form-control"
                           placeholder="Add a promo code (optional)" autocapitalize="characters" style="margin-bottom: 6px; width: 110%"><br/>
                    <label for="id_tags_category" class="sr-only">Tags Category</label>
                    <input type="text" class="form-control" readonly id="id_tags_category" placeholder="Add a Category Tag">
                    <select class="form-control" name="tags_category" id="id_tags_category">
                        <option value="1">FOOD</option>
                        <option value="2">TRAVEL</option>
                        <option value="3">FASHION</option>
                        <option value="4">TECHNOLOGY</option>
                        <option value="5">BOOKS/EDUCATION</option>
                        <option value="6">MUSIC</option>
                        <option value="7">FURNITURE</option>
                        <option value="8">STATIONARY & ART</option>
                        <option value="9">SKINCARE & BEAUTY</option>
                    </select><br/>
                    <label for="id_tags_type" class="sr-only">Tags Type</label>
                    <input type="text" class="form-control" readonly id="id_tags_type" placeholder="Add a Type Tag">
                    <select class="form-control" name="tags_type" id="id_tags_type">
                        <option value="1">FLASH SALE/DISCOUNT</option>
                        <option value="2">BUY MORE, SAVE MORE</option>
                        <option value="3">LOTTERY/COMPETITION</option>
                        <option value="4">GIFT BUNDLE/GIVEAWAY</option>
                        <option value="5">BUY 1 GET 1 FREE</option>
                        <option value="6">LOYALTY PROGRAM</option>
                        <option value="7">VOUCHER/COUPON</option>
                        <option value="8">FREE SHIPPING/RETURN</option>
                        <option value="9">OTER</option>
                    </select>

                </div>

                <button class="btn btn-primary" type="submit" name="submit">
                    Post!
                </button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
    {% else %}
    <h3>You aren't authorized to post for {{ business.name }} :(</h3>
    {% endifequal %}
{% endblock %}

templates/voucher/all_posts.html
{% extends "voucher/base.html" %}
{% load static %}
    {% block title_block %}
        Posts
    {% endblock %}

 {% block body_block %}
     <div class="jumbotron p-1" style="background-color: aliceblue">
         <div class="container">
             <h2 align="center">All Posts on VoucherMe!</h2>
         </div>
     </div>

     

     <center>
     <div class="container" style="width: 50%">
         <div class="form-group">
             <form role="form" method="get" action="{% url 'voucherMe:search' "posts" %}">
                 {% csrf_token %}
                 <div class="form-group">
                     <label for="id_search" class="sr-only">Search</label>
                     <input type="text" name="search" id="id_search" class="form-control"
                            placeholder="Find the Best Deals..." required autofocus style="margin-bottom: 6px">
                 </div>
                 <button class="btn btn-primary" type="submit" name="submit">
                    Search!
             </button>
             </form>
         </div>
     </div>
     </center>

      <center>
          {% if posts %}
              {% for post in posts %}
                  <div class="card">
                      <div class = "container">
                          <strong><a href="{% url 'voucherMe:show_post' post.business.slug post.id %}">{{ post.name }}</a></strong>
                          <br/>
                          by <a href="{% url 'voucherMe:show_business' post.business.slug %}">{{ post.business.name }}</a>
                          <br/>
                          {{ post.get_tags_category_display }} | {{ post.get_tags_type_display }}
                      </div>
                  </div>
                  <br>
              {% endfor %}
          {% else %}
              <p style="color: aliceblue"><strong>There are no posts on VoucherMe currently :(</strong></p>
          {% endif %}
    </center>
{% endblock %}

templates/voucher/base.html
<!DOCTYPE html>
{% load static %}
{% load voucher_me_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <title>
        VoucherMe - {% block title_block %}{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
        <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    
    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}" >
    </head>

    

    <body>
        <div class="custombg">
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'voucherMe:index' %}">VoucherMe!</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'voucherMe:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'voucherMe:about' %}">About us</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'voucherMe:all_businesses' %}">Businesses</a> </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'voucherMe:all_posts' %}">Posts</a> </li>

                        {% if user.is_authenticated %}
							<li class="nav-item"><a class="nav-link" href="{% url 'voucherMe:profile' user.username %}">Your Profile</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Sign Up</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>

         <div class="container-fluid">
            <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div style="background-image: url({% static 'images/ba.png' %}); background-size: cover; background-position: center">
                    <div class="sidebar-sticky">
                    <div style="position: absolute; top: 35%; background-image: url({% static 'images/background.png' %});">
                    {% block sidebar_block %}
                        <img src="{% static 'images/Logo.jpg' %} "alt="Our Amazing Logo" style="width:100%;height:140px;"/>
                        <br/><br/>
                        <p style="text-align:center"><strong>&middot; &copy; 2021 VoucherMe &middot;</strong> </p>
                        <p style="text-align: center"><a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    {% endblock %}
                    </div>
                    </div>
            </div>
                </nav>

                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                        {% block body_block %} {% endblock %}
                    <!-- FOOTER -->
                    <footer>
                        <br/>
                        <div align="right">
                            <p class="float-right">
                                <a href="https://www.instagram.com">
                                    <img src="{% static 'images/instagram.png' %}" style="height: 20%; width: 20%"/>
                                </a>
                            </p>
                        </div>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/script.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="{% static 'js/script2.js' %}" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="{% static 'js/script3.js' %}"></script>
        <script src="{% static 'js/script4.js' %}"></script>
    </body>
    </div>
</html>

templates/voucher/business.html
{% extends "voucher/base.html" %}
{% load static %}
{% block title_block %}
    {% if business %}
        {{ business.name }}
    {% else %}
        Unknown Business :(
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if business %}
        <div class="jumbotron p-1">
            <div class="container">
                <h2 align="center">Welcome to {{ business.name }}</h2>
            </div>
        </div>

        <div class="float-container">

            <div class="float-child" style="width: 27%;">
                {% if business.image %}
                    <img id="round" src="{{ business.image.url }}" alt="business_picture" style="width: 80%; height: 80%">
                {% else %}
                    <img id="round" src="{% static 'images/img_2.png' %}" alt="profile_picture" style="width: 40%">
                {% endif %}
            </div>
            <br><br>

            <div class="float-child" style="width: 38%">
                <p style="color: aliceblue"><strong>Popularity</strong></p>
                {% with ''|center:popularity as range %}
                    {% for i in range %}
                        <img src="{% static 'images/star.png' %}" alt="star" style="width: 5%; height: 5%">
                    {% endfor %}
                {% endwith %}<br/><br/>
                {% ifequal user business.user %}
                    <a href="{% url 'voucherMe:add_post' business.slug %}">
                        <button class="btn btn-info">Add a new post now!</button>
                    </a>
                {% endifequal %}
            </div>

            <div class="float-child">
                <center><p style="color: aliceblue"><strong>About</strong></p></center><br/>
                <p class="text" style="width: 100%">{{ business.description }}</p>
            </div>
        </div>
        <br/>
        <div align="left">
            {% if posts %}
                <h4 style="color: aliceblue" align="center">Posts</h4><br/>
                <section id="services">
                    <ul>
                        <li><strong><center> <p class="text" style="width: 100%"> Post Name</p> </strong> </li> <pre class="tab"> </pre>
                        <li><strong><center> <p class="text" style="width: 100%">Post visits</p> </strong></li> <pre class="tab"> </pre>
                        <li><strong><center> <p class="text" style="width: 100%">Tags </p></strong></li> <pre class="tab"> </pre>
                        <li><strong><center> <p class="text" style="width: 100%">Promo Code </p></strong></li><br>
                </section>

                <ul><br>
                    <section id="services">
                        {% for post in posts %}
                            <ul>
                                <li><strong><center><p class="text" style="width: 100%"><a href="{% url 'voucherMe:show_post' business.slug post.id %}">{{ post.name }}</a></p></center></strong></li>
                                <pre class="tab"> </pre>
                                <li><strong><center><p class="text">{{ post.visits }}</p></center></strong></li>
                                <pre class="tab"> </pre>
                                <li><center><p class="text" style="width: 100%">{{ post.get_tags_category_display }} | {{ post.get_tags_type_display }}</p></center></li>
                                <pre class="tab"> </pre>
                                {% if post.promo %}
                                    <li><strong><center><p class="text">{{ post.promo }} </p></center></strong></li>
                                {% else %}
                                    <li/>
                                {% endif %}
                            </ul><br>
                        {% endfor %}
                    </section>
                </ul><br>
            {% else %}
                <p style="color: aliceblue">There are no posts from <strong id="business">{{ business.name }} </strong> yet :(</p>
            {% endif %}
        </div>
    {% else %}
        <p style="color: aliceblue; font-weight: bold">You're lost wanderer, the business you're looking for does not exist</p>
    {% endif %}
    <br><br>
{% endblock %}

templates/voucher/index.html
{% extends "voucher/base.html" %}
{% load static %}

{% block title_block %}Home!{% endblock %}
{% block body_block %}

	<div class="jumbotron p-1">
      <div class="container">
          <h3 class="jumbotron-heading" align="center">Welcome to VoucherMe</h3>
      </div>
    </div>
<center>
	<div class="left column">
                  {% if posts %}
                      <h3 align="center" style="color: aliceblue">Top Trending Posts</h3><br/>
                      {% for post in posts %}
                          <div class="card">
                              <div class = "container">
                                  <strong><a href="{% url 'voucherMe:show_post' post.business.slug post.id %}">{{ post.name }}</a></strong>
                                  <br/>
                                  by <a href="{% url 'voucherMe:show_business' post.business.slug %}">{{ post.business.name }}</a>
                                  <br/>
                                  {{ post.get_tags_category_display }} | {{ post.get_tags_type_display }}
                              </div>
                          </div>
                          <br>
                      {% endfor %}
                  {% else %}
                      <p style="color: aliceblue; font-weight: bold">There are no posts on VoucherMe currently :(</p>
                  {% endif %}
    </div>

              <br>

    <div class="right column">
              {% if businesses %}
                  <h3 align="center" style="color: aliceblue">Most Popular Businesses</h3><br/>
                  {% for business in businesses %}
                      <div class="card">
                          {% if business.image %}
                              <center>
                              <div class="bus-image">
                                  <img src="{{ business.image.url}}" alt="Businesses chosen image"/>
                              </div>
                          {% else %}
                              <center>
                              <div class="bus-image">
                                  <img src="{% static 'images/img_2.png' %}">
                              </div>
                          {% endif %}
                          <div class = "container">
                              <a href="{% url 'voucherMe:show_business' business.slug %}">{{ business.name }}</a>
                          </div>
                      </div>
                      <br>
                  {% endfor %}
              {% else %}
                  <p style="color: aliceblue; font-weight: bold">There are no businesses register on VoucherMe yet :(</p>
              {% endif %}
    </div>
</center>

{% endblock %}

templates/voucher/post.html
{% extends "voucher/base.html" %}
{% load static %}
    {% block title_block %}
        {% if post %}
            {{ post.name }}
        {% else %}
            Unknown Post :(
        {% endif %}
    {% endblock %}

    {% block body_block %}
        <script src="{% static 'js/functions.js' %}"></script>
        
            {% if post %}
                <div class="jumbotron p-1">
                    <div class="container">
                        <h3 class="jumbotron-heading" align="center">"{{ post.name }}" by
                            <a href="{% url 'voucherMe:show_business' post.business.slug%}">{{ post.business }}</a>
                        </h3>
                    </div>
                </div>
                <div align="center">
                    <p style="color: aliceblue"><strong>Description</strong></p>
                    <p class="text"> {{ post.description }}</p><br/>
                    <p style="color: aliceblue"><strong>Category</strong></p>
                    <p class="text">{{ post.get_tags_category_display }}</p><br/>
                    <p style="color: aliceblue"><strong>Type</strong></p>
                    <p class="text">{{ post.get_tags_type_display }}</p><br/>
                {% if post.promo %}
                    <p style="color: aliceblue"><strong>Promo Code</strong></p>
                    <input type="text" value= {{ post.promo }} id="CopyCode" style="text-transform: uppercase; text-align: center"/>
                    <br/><br/>
                    <button onclick="copyText()"class="btn btn-info">Copy Promo!</button><br/>
                {% endif %}
                </div>
            {% else %}
                <p style="color: aliceblue"><strong>You're lost wanderer, post not found :(</strong></p>
            {% endif %}
        <br><br>
    {% endblock %}

templates/voucher/search.html
{% extends "voucher/base.html" %}
{% load static %}
    {% block title_block %}
        Search
    {% endblock %}

 {% block body_block %}
     
     <div class="jumbotron p-1">
         <div class="container">
             <h2 align="center">Search</h2>
         </div>
     </div>
     <div align="center">
     {% if results %}
         <h4 style="color:aliceblue">Here are the best results we could find!</h4>

     {% else %}
         <h4 style="color:aliceblue">No matching results for your query :(</h4>
     {% endif %}
     </div>
     {% ifequal type "business" %}
         {% for business in results %}
             <center>
             <div class="card">
                 {% if business.image %}
                     <center>
                     <div class="bus-image">
                         <img src="{{ business.image.url}}" alt="Businesses chosen image"/>
                     </div>
                 {% else %}
                     <center>
                     <div class="bus-image">
                         <img src="{% static 'images/img_2.png' %}">
                     </div>
                 {% endif %}
                 <div class = "container">
                     <a href="{% url 'voucherMe:show_business' business.slug %}">{{ business.name }}</a>
                 </div>
             </div>
             <br>
             </center>
             <br>
         {% endfor %}

     {% else %}
         {% for post in results %}
             <center>
             <div class="card">
                 <div class = "container">
                     <strong><a href="{% url 'voucherMe:show_post' post.business.slug post.id %}">{{ post.name }}</a></strong>
                     <br/>
                     by <a href="{% url 'voucherMe:show_business' post.business.slug %}">{{ post.business.name }}</a>
                     <br/>
                     {{ post.get_tags_category_display }} | {{ post.get_tags_type_display }}
                 </div>
             </div>
             <br>
             </center>
             <br>
         {% endfor %}
     {% endifequal %}

{% endblock %}